server:
  port: 8771
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
env:  prod
branch: master
    
    
